---                                                                           
  kind: pipeline                                            
  type: docker
  name: build-and-deploy                                                        
                                                                                
  trigger:                                                                      
    branch: [main]                                                              
    event: [push]                                           
                                                                                
  steps:
    - name: build                                                               
      image: plugins/docker                                 
      settings:                                                                 
        repo: git.samagsteribbe.nl/admin/dragonsstash
        registry: git.samagsteribbe.nl                                          
        tags:                                               
          - latest
          - "${DRONE_COMMIT_SHA:0:8}"
        username:                                                               
          from_secret: gitea_username
        password:                                                               
          from_secret: gitea_password                       

    - name: deploy
      image: appleboy/drone-ssh
      settings:
        key:                                                                    
          from_secret: ssh_key
      environment:                                                              
        PLUGIN_HOST: 192.168.68.68                          
        PLUGIN_USERNAME: sam                                                    
        PLUGIN_PORT: "22"                                   
        PLUGIN_SCRIPT: "cd /opt/stacks/DragonsStash && docker compose pull && 
  docker compose up -d"
